apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3
  namespace: vllm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: gp3
  volumeMode: Filesystem
