apiVersion: v1
kind: Service
metadata:
  name: qwen3
  namespace: vllm
spec:
  type: ClusterIP
  selector:
    app: qwen3
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
