[project]
name = "vision-on-the-edge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "brevitas>=0.12.1",
    "mlflow[auth]>=3.1.4",
    "numpy>=1.26.4",
    "onnx>=1.16.1",
    "onnx2tf>=1.26.4",
    "optuna>=4.6.0",
    "tensorflow>=2.16.1",
    "torch>=2.8.0",
    "torchao>=0.14.1",
    "torchvision>=0.23.0",
    "zenml[server]>=0.82.0",
]
