[files]
extend-exclude = [
    ".gitignore",
    "LICENSE",
    ".*",
    "*.csv"
]
ignore-hidden = true
ignore-dot = true


[default]
locale = "en-gb"
extend-ignore-re = [
    # Ignore lines that end with `# spellchecker:disable-line`
    "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
    # Ignore the line after `# spellchecker:ignore-next-line`:
    "(#|//)\\s*spellchecker:ignore-next-line\\n.*",
    # Ignore blocks between `# spellchecker:off` and `# spellchecker:on`
    "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
]

[default.extend-words]
"normalize" = "normalize"
"artifact" = "artifact"
"Artifact" = "Artifact"
"artifacts" = "artifacts"
"Authorization" = "Authorization"
"amortization" = "amortization"
"optimizer" = "optimizer"
"flavor" = "flavor"
"normalized" = "normalized"
