apiVersion: v1
kind: Service
metadata:
  name: rag-api
  namespace: rag-api
  labels:
    app: rag-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: rag-api
