[project]
name = "experiment-tracking-for-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dvc>=3.64.2",
    "mlflow[auth]>=3.7.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "zenml[server]>=0.92.0",
]
