[env:esp32s3]
platform = espressif32
; Change this to match your ESP32-S3 board (e.g. esp32-s3-devkitc-1, esp32-s3-devkitm-1).
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/tanakamasayuki/Arduino_TensorFlowLite_ESP32.git
lib_ldf_mode = deep+
build_flags =
    -I${PROJECT_LIBDEPS_DIR}/${PIOENV}/TensorFlowLite_ESP32/src
    -I${PROJECT_LIBDEPS_DIR}/${PIOENV}/TensorFlowLite_ESP32/src/tensorflow
    -I${PROJECT_LIBDEPS_DIR}/${PIOENV}/TensorFlowLite_ESP32/src/third_party/flatbuffers/include
