apiVersion: v1
kind: Service
metadata:
  name: context-forge
  namespace: context-forge
spec:
  type: ClusterIP
  selector:
    app: context-forge
  ports:
    - name: http
      port: 4444
      targetPort: 4444
